baseURL = "https://poprocks.dev/"
languageCode = "en-us"
title = "poprocks.dev"
theme = "liquorice"

[permalinks]
  posts = "/:title"

[params]
  author = "Robert Paprocki"
  description = "Brain Dumps"
